### PR TITLE
Atlantis

### PR DESCRIPTION
**Pull request by botsights**

### CODE REVIEW

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1
Upgrading modules...
- branch_protection in ../modules/branch_protection

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider



```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure": exit status 1

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.


```

**Comment by botsights** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 13: field steps not found in type raw.Workflow
  line 17: field steps not found in type raw.Workflow
```

**Comment by botsights** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure` workspace: `default`

**Plan Error**
```
running "/Users/matejsnuderl/.atlantis/bin/terraform0.12.26 plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure": exit status 1

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.


```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
running "/Users/matejsnuderl/.atlantis/bin/terraform0.12.26 plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1

Error: Invalid for_each argument

  on main.tf line 28, in resource "github_membership" "admins":
  28:   for_each = local.admins

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type tuple.


```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
running "/Users/matejsnuderl/.atlantis/bin/terraform0.12.26 plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1

Error: Call to unknown function

  on main.tf line 28, in resource "github_membership" "admins":
  28:   for_each = set(local.admins)
    |----------------
    | local.admins is tuple with 3 elements

There is no function named "set". Did you mean "sort"?


```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
running "/Users/matejsnuderl/.atlantis/bin/terraform0.12.26 plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: If `anonymous` is false, `token` is required.

  on providers.tf line 1, in provider "github":
   1: provider "github" {



```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # github_membership.admins["Meemaw"] will be created
+ resource "github_membership" "admins" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "Meemaw"
    }

  # github_membership.admins["botsights"] will be created
+ resource "github_membership" "admins" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "botsights"
    }

  # github_membership.admins["snuderl"] will be created
+ resource "github_membership" "admins" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "admin"
      + username = "snuderl"
    }

  # github_membership.botsights_membership will be destroyed
- resource "github_membership" "botsights_membership" {
      - etag     = "W/\"7cf2650833397c059236e581df513643\"" -> null
      - id       = "insights-io:botsights" -> null
      - role     = "admin" -> null
      - username = "botsights" -> null
    }

  # github_membership.meemaw_membership will be destroyed
- resource "github_membership" "meemaw_membership" {
      - etag     = "W/\"9bca3680276f85866e58a429c081be96\"" -> null
      - id       = "insights-io:Meemaw" -> null
      - role     = "admin" -> null
      - username = "Meemaw" -> null
    }

  # github_membership.snuderl_membership will be destroyed
- resource "github_membership" "snuderl_membership" {
      - etag     = "W/\"db758e984fe673cca1c2c781ac345ef7\"" -> null
      - id       = "insights-io:snuderl" -> null
      - role     = "admin" -> null
      - username = "snuderl" -> null
    }

Plan: 3 to add, 0 to change, 3 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false -no-color \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1
github_membership.meemaw_membership: Destroying... [id=insights-io:Meemaw]
github_membership.snuderl_membership: Destroying... [id=insights-io:snuderl]
github_membership.botsights_membership: Destroying... [id=insights-io:botsights]
github_membership.admins["botsights"]: Creating...
github_membership.admins["snuderl"]: Creating...
github_membership.admins["Meemaw"]: Creating...
github_membership.meemaw_membership: Destruction complete after 1s
github_membership.snuderl_membership: Destruction complete after 2s
github_membership.admins["botsights"]: Creation complete after 9s [id=insights-io:botsights]
github_membership.admins["snuderl"]: Creation complete after 9s [id=insights-io:snuderl]
github_membership.admins["Meemaw"]: Creation complete after 9s [id=insights-io:Meemaw]

Error: DELETE https://api.github.com/orgs/insights-io/memberships/botsights: 403 Cannot remove the last owner []



```
</details>

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # github_membership.botsights_membership will be destroyed
- resource "github_membership" "botsights_membership" {
      - etag     = "W/\"7cf2650833397c059236e581df513643\"" -> null
      - id       = "insights-io:botsights" -> null
      - role     = "admin" -> null
      - username = "botsights" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

```diff
github_membership.botsights_membership: Destroying... [id=insights-io:botsights]
github_membership.botsights_membership: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

```

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # github_membership.admins["snuderl"] will be updated in-place
~ resource "github_membership" "admins" {
        etag     = "W/\"719dbe2275e5453ac670bb72a514a6c1\""
        id       = "insights-io:snuderl"
      ~ role     = "reinstate" -> "admin"
        username = "snuderl"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
terraform apply

**Comment by botsights** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

```diff
github_membership.admins["snuderl"]: Modifying... [id=insights-io:snuderl]
github_membership.admins["snuderl"]: Modifications complete after 1s [id=insights-io:snuderl]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github/default.tfplan\"" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": exit status 1

Error: Reference to undeclared local value

  on teams.tf line 10, in resource "github_team_membership" "infrastructure_maintainers":
  10:   for_each = toset(local.infrastructure_members)

A local value with the name "infrastructure_members" has not been declared.


```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Comment by botsights** [comment]
**Plan Error**
```
parsing atlantis.yaml: workflows: (authenticated: (plan: (steps: (0: "if [ $USERNAME != \"Meemaw\" ]; then exit 1; fi" is not a valid step type, maybe you omitted the 'run' key.).).).).
```

**Comment by botsights** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by botsights** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by snuderl** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff
sh: line 0: [: !=: unary operator expected


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff
sh: line 0: [: !=: unary operator expected


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff
Checking if  is allowed to run atlantis apply

sh: line 0: [: !=: unary operator expected


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff
Checking if Meemaw is allowed to run atlantis apply


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
exit status 1: running "if [ $USER_NAME != \"Meemawe\" ]; then exit 1; fi" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": 

Checking if Meemaw is allowed to run atlantis apply

```

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
exit status 1: running "if [ $USER_NAME != \"Meemawe\" ]; then echo \\\"Sorry $USER_NAME, you are not authorized to plan.\\\" && exit 1; fi" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": 
"Sorry Meemaw, you are not authorized to plan."


```

**Comment by snuderl** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

**Plan Error**
```
exit status 1: running "if [ $USER_NAME != \"Meemaw\" ]; then echo \\\"Sorry $USER_NAME, you are not authorized to plan.\\\" && exit 1; fi" in "/Users/matejsnuderl/.atlantis/repos/insights-io/Insight/8/default/infrastructure/terraform/github": 
"Sorry snuderl, you are not authorized to plan."


```

**Comment by Meemaw** [comment]
atlantis plan

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/github` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_team.infrastructure will be created
+ resource "github_team" "infrastructure" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + name    = "infrastructure"
      + node_id = (known after apply)
      + privacy = "secret"
      + slug    = (known after apply)
    }

  # github_team_membership.infrastructure_maintainers["Meemaw"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "Meemaw"
    }

  # github_team_membership.infrastructure_maintainers["snuderl"] will be created
+ resource "github_team_membership" "infrastructure_maintainers" {
      + etag     = (known after apply)
      + id       = (known after apply)
      + role     = "maintainer"
      + team_id  = (known after apply)
      + username = "snuderl"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/github`
* :put_litter_in_its_place: To **delete** this plan click [here](http://0018d28b1afb.ngrok.io/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fgithub%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/github`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/github` workspace: `default`

```diff
github_team.infrastructure: Creating...
github_team.infrastructure: Creation complete after 2s [id=3885512]
github_team_membership.infrastructure_maintainers["snuderl"]: Creating...
github_team_membership.infrastructure_maintainers["Meemaw"]: Creating...
github_team_membership.infrastructure_maintainers["Meemaw"]: Creation complete after 2s [id=3885512:Meemaw]
github_team_membership.infrastructure_maintainers["snuderl"]: Creation complete after 3s [id=3885512:snuderl]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

```

**Comment by botsights** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infrastructure/terraform/github` workspace: `default`

**Pull request merged**
