### PR TITLE
chore: add total monthly budget

### PR DESCRIPTION
**Pull request by Meemaw**

### CODE REVIEW

**Comment by botsights** [comment]
Ran Plan for dir: `infrastructure/terraform/management/budget` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_budgets_budget.total_monthly will be created
+ resource "aws_budgets_budget" "total_monthly" {
      + account_id        = (known after apply)
      + budget_type       = "COST"
      + cost_filters      = (known after apply)
      + id                = (known after apply)
      + limit_amount      = "1"
      + limit_unit        = "USD"
      + name              = "budget-total-monthly"
      + name_prefix       = (known after apply)
      + time_period_end   = "2087-06-15_00:00"
      + time_period_start = "2020-06-01_00:00"
      + time_unit         = "MONTHLY"

      + cost_types {
          + include_credit             = (known after apply)
          + include_discount           = (known after apply)
          + include_other_subscription = (known after apply)
          + include_recurring          = (known after apply)
          + include_refund             = (known after apply)
          + include_subscription       = (known after apply)
          + include_support            = (known after apply)
          + include_tax                = (known after apply)
          + include_upfront            = (known after apply)
          + use_amortized              = (known after apply)
          + use_blended                = (known after apply)
        }

      + notification {
          + comparison_operator        = "GREATER_THAN"
          + notification_type          = "FORECASTED"
          + subscriber_email_addresses = [
              + "ematej.snuderl@gmail.com",
            ]
          + subscriber_sns_topic_arns  = []
          + threshold                  = 100
          + threshold_type             = "PERCENTAGE"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d infrastructure/terraform/management/budget`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.dev.snuderls.eu/lock?id=insights-io%252FInsight%252Finfrastructure%252Fterraform%252Fmanagement%252Fbudget%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d infrastructure/terraform/management/budget`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by Meemaw** [comment]
atlantis apply

**Comment by botsights** [comment]
Ran Apply for dir: `infrastructure/terraform/management/budget` workspace: `default`

```diff
aws_budgets_budget.total_monthly: Creating...
aws_budgets_budget.total_monthly: Creation complete after 3s [id=712861137634:budget-total-monthly]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by botsights** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infrastructure/terraform/management/budget` workspace: `default`

**Pull request merged**
